### ISSUE TITLE
Not Able to See the data on the Serial monitor

### ISSUE THREAD

**Issue by shivalingaraju** [smarmengol/Modbus-Master-Slave-for-Arduino#23]
I am able to achieve RS485 Modbus communication. At the other end device, I am able to see proper acknowledgment.
![modbus slave](https://cloud.githubusercontent.com/assets/27272619/25380013/60651c8a-29cc-11e7-8100-5e99094cee72.png)

but , I am not able to see any data on Arduino serial comport please do help me.  

![serial comport](https://cloud.githubusercontent.com/assets/27272619/25379517/e65ecd10-29ca-11e7-87ef-11797f846e5e.png)

**Comment by geoffmiles** [comment]
Im having the same problem. To my knowledge the response from the modbus slave device is processed by the function get_FC3 which moves them from the au8buffer to au16reg however I am struggling to get data from them. I used a 3rd party program to ensure I am getting the correct query from my arduino and Ive used the same program to send that query to the modbus device and received the expected response. So I know the data is there I am just having some issues displaying them.

**Comment by smarmengol** [comment]
The Arduino Serial Monitor shows ASCII data. As you know, the Modbus RTU
protocol handles raw binary data. Therefore it only shows ⬜ and wrong
symbols instead of the real values.

When I wrote this library, I used third-party simulators either for the
Master or for the Slave. I recommend you these:

QModbus: http://qmodbus.sourceforge.net/

Modpoll and it's slave Variant: http://www.modbusdriver.com/modpoll.html

Multiway: https://www.support-omron.fr/Multiway.php

I hope that this would help you. You can also find further information in
my blog:

http://arduino-experience.blogspot.com.es/

Regards,

SAMUEL

El dia 29/04/2017 18:42, "Geoffrey G Miles" <notifications@github.com> va
escriure:

**Comment by shivalingaraju** [comment]
Thank you for your response, sir (smarmengol),
Qmodbus version 0.2.1 and 0.1.0 I downloaded and tried I am getting following errors.

if I click on send,
![4](https://cloud.githubusercontent.com/assets/27272619/25605789/0f4eb9be-2f2b-11e7-8a5c-1de955bd40a3.png)

sometimes I am getting this error for version 0.2.1 and for 0.1.0 also I am getting the same error.

![5](https://cloud.githubusercontent.com/assets/27272619/25605849/79449a5a-2f2b-11e7-8756-951572f4ec99.png)

Version 0.2.0 also I downloaded by I am not getting how to use it, sir.

**Comment by shivalingaraju** [comment]
please do update if anybody got any solution to fetch the data using RS485 communication protocol.

**Comment by smarmengol** [comment]
Regarding to the RS485, look at this:

http://arduino-experience.blogspot.com.es/2016/01/rs-485-implementation-on-arduino.html?m=1



El dia 04/05/2017 06:34, "shivalingaraju" <notifications@github.com> va
escriure:

please do update if anybody got any solution to fetch the data using RS485
communication protocol.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/smarmengol/Modbus-Master-Slave-for-Arduino/issues/23#issuecomment-299095138>,
or mute the thread

**Comment by shivalingaraju** [comment]
Thank you i will look into it

**Comment by shivalingaraju** [comment]
thank you for your help and support it worked.
