### ISSUE TITLE
RS485 Half Duplex on SoftWareSerial

### ISSUE THREAD

**Issue by HiTec-Tenshi** [smarmengol/Modbus-Master-Slave-for-Arduino#31]
Hi,
Thank you for this library and the examples.
I have a question.

#include <ModbusRtu.h>
#include <SoftwareSerial.h>
#define rxPin 2
#define txPin 3
#define mySerial Serial1

#define ID   0 // 0 = Master > Slave ID
#define Port   1
#define RS485_pin   4

SoftwareSerial mySerial( rxPin, txPin )

master.begin( 38400, SERIAL_8E1 )

why this does not work?

and if you change 

// Address, Serialport, Pin for RS485 (DE/RE) 
Modbus master(ID, Port, RS485_pin); // this is master and RS-232 or USB-FTDI

to

// Address, Pin for RS485 (DE/RE), Serialport
Modbus master(ID, RS485_pin, Port); // this is master and RS-232 or USB-FTDI

you could use RS485 Half Duplex on SoftWareSerial easier.

**Comment by Surbyte** [comment]
You ddn´t understand how to inicialize the constructor.
Modbus(uint8_t u8id, uint8_t u8serno, uint8_t u8txenpin);
   *  u8id      : node id = 0 for master, = 1..247 for slave
   *  u8serno   : serial port (use 0 for Serial)
   *  u8txenpin : 0 for RS-232 and USB-FTDI 
   *               or any pin number > 1 for RS-485
   *  uint8_t u8serno; //!< serial port: 0-Serial, 
   *                                     1..3-Serial1..Serial3;  Mega/DUE x ejemplo
   *                                     4: use software serial
   *  uint8_t u8txenpin; //!< flow control pin: 0 =USB or RS-232 mode, >0 =RS-485 mode


When you casually invert the configuration it works but why? Because you have placed RS485_pin whose value is 4 as a port type and that is what corresponds to SoftwareSerial and u8txenpin is pin 1 same as TX of Serial. 
Your master config must be 
Modbus master(ID, 4, RS485_pin); // So simple!!
